client_id: 3MVG9QDx8IX8nP5RpaLJu2y8S4P3.C_na8FcsrAEJ228sG2hQHTcHblZp64brTxaQAib75.GzrFlygjto2VXU
client_secret: 7527222527070255933
username: mess@cloudspokes.com.dev091
password: @4H>yd2NZW
debugging: true